k = 0.5
K=elK(k)
x = 0.25*K
fprintf('cd %.16g \n',(ijcd(jcd(x,k),k)-x)/eps);
fprintf('cn %.16g \n',(ijcn(jcn(x,k),k)-x)/eps);
fprintf('cs %.16g \n',(ijcs(jcs(x,k),k)-x)/eps);
fprintf('dc %.16g \n',(ijdc(jdc(x,k),k)-x)/eps);
fprintf('dn %.16g \n',(ijdn(jdn(x,k),k)-x)/eps);
fprintf('ds %.16g \n',(ijds(jds(x,k),k)-x)/eps);
fprintf('nc %.16g \n',(ijnc(jnc(x,k),k)-x)/eps);
fprintf('nd %.16g \n',(ijnd(jnd(x,k),k)-x)/eps);
fprintf('ns %.16g \n',(ijns(jns(x,k),k)-x)/eps);
fprintf('sc %.16g \n',(ijsc(jsc(x,k),k)-x)/eps);
fprintf('sd %.16g \n',(ijsd(jsd(x,k),k)-x)/eps);
fprintf('sn %.16g \n',(ijsn(jsn(x,k),k)-x)/eps);
m = k^2;
fprintf('mcd %.16g \n',(mijcd(mjcd(x,m),m)-x)/eps);
fprintf('mcn %.16g \n',(mijcn(mjcn(x,m),m)-x)/eps);
fprintf('mcs %.16g \n',(mijcs(mjcs(x,m),m)-x)/eps);
fprintf('mdc %.16g \n',(mijdc(mjdc(x,m),m)-x)/eps);
fprintf('mdn %.16g \n',(mijdn(mjdn(x,m),m)-x)/eps);
fprintf('mds %.16g \n',(mijds(mjds(x,m),m)-x)/eps);
fprintf('mnc %.16g \n',(mijnc(mjnc(x,m),m)-x)/eps);
fprintf('mnd %.16g \n',(mijnd(mjnd(x,m),m)-x)/eps);
fprintf('mns %.16g \n',(mijns(mjns(x,m),m)-x)/eps);
fprintf('msc %.16g \n',(mijsc(mjsc(x,m),m)-x)/eps);
fprintf('msd %.16g \n',(mijsd(mjsd(x,m),m)-x)/eps);
fprintf('msn %.16g \n',(mijsn(mjsn(x,m),m)-x)/eps);